project_id = "vfnqvwtcjtclprapzlvm"

[functions.mj-ai]
verify_jwt = false

[functions.paystack]
verify_jwt = false

[functions.dynamic-pricing]
verify_jwt = false

[functions.create-booking]
verify_jwt = false

[functions.send-cancellation-email]
verify_jwt = false

[functions.ota-booking-webhook]
verify_jwt = false
