// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vfnqvwtcjtclprapzlvm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmbnF2d3RjanRjbHByYXB6bHZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIxMTA4MzIsImV4cCI6MjA4NzY4NjgzMn0.em2_M7j0ZlbxMvWe5GFxBr0mOx_tgxeBYA2QBAdkZmo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});